# Code generated by protoc-gen-rbi. DO NOT EDIT.
# source: broken_field_name.proto
# typed: strict

class Example::Broken_field_name
  include ::Google::Protobuf::MessageExts
  extend ::Google::Protobuf::MessageExts::ClassMethods

  # Constants of the form Constant_1 are invalid. We've declined to type this as a result, taking a hash instead.
  sig { params(args: T::Hash[T.untyped, T.untyped]).void }
  def initialize(args); end

  sig { returns(String) }
  def name
  end

  sig { params(value: String).void }
  def name=(value)
  end

  sig { void }
  def clear_name
  end

  sig { returns(String) }
  def Field_name_1
  end

  sig { params(value: String).void }
  def Field_name_1=(value)
  end

  sig { void }
  def clear_Field_name_1
  end

  sig { params(field: String).returns(T.untyped) }
  def [](field)
  end

  sig { params(field: String, value: T.untyped).void }
  def []=(field, value)
  end

  sig { returns(T::Hash[Symbol, T.untyped]) }
  def to_h
  end

  sig { params(str: String).returns(Example::Broken_field_name) }
  def self.decode(str)
  end

  sig { params(msg: Example::Broken_field_name).returns(String) }
  def self.encode(msg)
  end

  sig { params(str: String, kw: T.untyped).returns(Example::Broken_field_name) }
  def self.decode_json(str, **kw)
  end

  sig { params(msg: Example::Broken_field_name, kw: T.untyped).returns(String) }
  def self.encode_json(msg, **kw)
  end

  sig { returns(::Google::Protobuf::Descriptor) }
  def self.descriptor
  end
end
