package main

import (
	"log"
	"strings"
	"text/template"

	"github.com/coinbase/protoc-gen-rbi/ruby_types"

	pgs "github.com/lyft/protoc-gen-star"
	pgsgo "github.com/lyft/protoc-gen-star/lang/go"
)

type rbiModule struct {
	*pgs.ModuleBase
	ctx pgsgo.Context
	tpl *template.Template
	serviceTpl *template.Template
}

func RBI() *rbiModule { return &rbiModule{ModuleBase: &pgs.ModuleBase{}} }

func (m *rbiModule) InitContext(c pgs.BuildContext) {
	m.ModuleBase.InitContext(c)
	m.ctx = pgsgo.InitContext(c.Parameters())

	funcs := map[string]interface{}{
		"increment": m.increment,
		"rubyModules": ruby_types.RubyModules,
		"rubyPackage": ruby_types.RubyPackage,
		"rubyMessageType": ruby_types.RubyMessageType,
		"rubyGetterFieldType": ruby_types.RubyGetterFieldType,
		"rubySetterFieldType": ruby_types.RubySetterFieldType,
		"rubyInitializerFieldType": ruby_types.RubyInitializerFieldType,
		"rubyFieldValue": ruby_types.RubyFieldValue,
		"rubyMethodParamType": ruby_types.RubyMethodParamType,
		"rubyMethodReturnType": ruby_types.RubyMethodReturnType,
	}

	m.tpl = template.Must(template.New("rbi").Funcs(funcs).Parse(tpl))
	m.serviceTpl = template.Must(template.New("rbiService").Funcs(funcs).Parse(serviceTpl))
}

func (m *rbiModule) Name() string { return "rbi" }

func (m *rbiModule) Execute(targets map[string]pgs.File, pkgs map[string]pgs.Package) []pgs.Artifact {
	for _, t := range targets {
		m.generate(t)

		grpc, err := m.ctx.Params().BoolDefault("grpc", true)
		if err != nil {
			log.Panicf("Bad parameter: grpc\n")
		}

		if len(t.Services()) > 0 && grpc {
			m.generateServices(t)
		}
	}
	return m.Artifacts()
}

func (m *rbiModule) generate(f pgs.File) {
	op := strings.TrimSuffix(f.InputPath().String(), ".proto") + "_pb.rbi"
	m.AddGeneratorTemplateFile(op, m.tpl, f)
}

func (m *rbiModule) generateServices(f pgs.File) {
	op := strings.TrimSuffix(f.InputPath().String(), ".proto") + "_services_pb.rbi"
	m.AddGeneratorTemplateFile(op, m.serviceTpl, f)
}

func (m *rbiModule) increment(i int) int {
	return i + 1
}

func main() {
	pgs.Init(
		pgs.DebugEnv("DEBUG"),
	).RegisterModule(
		RBI(),
	).RegisterPostProcessor(
		pgsgo.GoFmt(),
	).Render()
}

const tpl = `# Code generated by protoc-gen-rbi. DO NOT EDIT.
# source: {{ .InputPath }}
# typed: strict
{{ range rubyModules . }}
module {{ . }}; end{{ end }}
{{ range .AllMessages }}
class {{ rubyMessageType . }}
  include Google::Protobuf
  include Google::Protobuf::MessageExts
{{ if gt (len .Fields) 0 }}
  sig do
    params({{ $index := 0 }}{{ range .Fields }}{{ if gt $index 0 }},{{ end }}{{ $index = increment $index }}
      {{ .Name }}: {{ rubyInitializerFieldType . }}{{ end }}
    ).void
  end
  def initialize({{ $index := 0 }}{{ range .Fields }}{{ if gt $index 0 }},{{ end }}{{ $index = increment $index }}
    {{ .Name }}: {{ rubyFieldValue . }}{{ end }}
  )
  end
{{ end }}{{ range .Fields }}
  sig { returns({{ rubyGetterFieldType . }}) }
  def {{ .Name }}
  end

  sig { params(value: {{ rubySetterFieldType . }}).void }
  def {{ .Name }}=(value)
  end
{{ end }}end
{{ end }}{{ range .AllEnums }}
module {{ rubyMessageType . }}{{ range .Values }}
  {{ .Name }} = T.let({{ .Value }}, Integer){{ end }}

  sig { params(value: Integer).returns(Symbol) }
  def lookup(value)
  end
end
{{ end }}`

const serviceTpl = `# Code generated by protoc-gen-rbi. DO NOT EDIT.
# source: {{ .InputPath }}
# typed: strict
{{ range .Services }}
module {{ rubyPackage .File }}::{{ .Name }}
  class Service
    include GRPC::GenericService
  end

  class Stub
    sig do
      params(
        host: String,
        creds: T.any(GRPC::Core::ChannelCredentials, Symbol),
        kw: T::Hash[Symbol, T.untyped]
      ).void
    end
    def initialize(host, creds, **kw)
    end{{ range .Methods }}

    sig do
      params(
        request: {{ rubyMethodParamType . }}
      ).returns({{ rubyMethodReturnType . }})
    end
    def {{ .Name.LowerSnakeCase }}(request)
    end{{ end }}
  end
end
{{ end }}`
