version: 2
jobs:
  build:
    docker:
      - image: cimg/ruby:3.1.2
    steps:
      - checkout
      - run:
          name: "Install Go"
          command: |
            curl -sSL "https://dl.google.com/go/go1.13.5.linux-amd64.tar.gz" | sudo tar -xz -C /usr/local/
            echo "export PATH=$PATH:/usr/local/go/bin:/home/circleci/go/bin" >> $BASH_ENV
      - run:
          name: "Install Bundler"
          command: |
            gem install bundler
      - run:
          name: "Test"
          command: |
            make test
  salus:
    machine: true
    steps:
      - checkout
      - run: docker run -t -v $(pwd):/home/repo coinbase/salus

workflows:
  version: 2
  build:
    jobs:
      - build
      - salus
