# Code generated by protoc-gen-rbi. DO NOT EDIT.
# source: example.proto
# typed: strict

# some description for request message
class Example::Request < ::Google::Protobuf::AbstractMessage
  sig do
    params(
      name: T.nilable(String),
      nicknames: T.nilable(T::Array[String]),
      attributes: T.nilable(T::Hash[String, String])
    ).void
  end
  def initialize(
    name: "",
    nicknames: [],
    attributes: ::Google::Protobuf::Map.new(:string, :string)
  )
  end

  # some description for name field
  sig { returns(String) }
  def name
  end

  # some description for name field
  sig { params(value: String).void }
  def name=(value)
  end

  # some description for name field
  sig { void }
  def clear_name
  end

  # some description for repeated field
  sig { returns(T::Array[String]) }
  def nicknames
  end

  # some description for repeated field
  sig { params(value: ::Google::Protobuf::RepeatedField[String]).void }
  def nicknames=(value)
  end

  # some description for repeated field
  sig { void }
  def clear_nicknames
  end

  # some description for map field
  sig { returns(T::Hash[String, String]) }
  def attributes
  end

  # some description for map field
  sig { params(value: ::Google::Protobuf::Map[String, String]).void }
  def attributes=(value)
  end

  # some description for map field
  sig { void }
  def clear_attributes
  end
end

# some description for responsee message that is multi line and has a # in it
# that needs to be escaped
class Example::Response < ::Google::Protobuf::AbstractMessage
  sig do
    params(
      greeting: T.nilable(String)
    ).void
  end
  def initialize(
    greeting: ""
  )
  end

  # some description for greeting field
  sig { returns(String) }
  def greeting
  end

  # some description for greeting field
  sig { params(value: String).void }
  def greeting=(value)
  end

  # some description for greeting field
  sig { void }
  def clear_greeting
  end
end
