# Code generated by protoc-gen-rbi. DO NOT EDIT.
# source: broken_field_name.proto
# typed: strict

class Example::Broken_field_name
  include ::Google::Protobuf::MessageExts
  extend ::Google::Protobuf::MessageExts::ClassMethods

  # Constants of the form Constant_1 are invalid. We've declined to type this as a result, taking a hash instead.
  sig { params(args: T::Hash[T.untyped, T.untyped]).void }
  def initialize(args); end

  sig { returns(String) }
  def name
  end

  sig { params(value: String).void }
  def name=(value)
  end

  sig { void }
  def clear_name
  end

  sig { returns(String) }
  def Field_name_1
  end

  sig { params(value: String).void }
  def Field_name_1=(value)
  end

  sig { void }
  def clear_Field_name_1
  end
end
