# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: broken_field_name.proto

require 'google/protobuf'

Google::Protobuf::DescriptorPool.generated_pool.build do
  add_file("broken_field_name.proto", :syntax => :proto3) do
    add_message "example.broken_field_name" do
      optional :name, :string, 1
      optional :Field_name_1, :string, 2
    end
  end
end

module Example
  Broken_field_name = Google::Protobuf::DescriptorPool.generated_pool.lookup("example.broken_field_name").msgclass
end
