# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: broken_package_name.proto

require 'google/protobuf'

Google::Protobuf::DescriptorPool.generated_pool.build do
  add_file("broken_package_name.proto", :syntax => :proto3) do
    add_message "package2test.Message2test" do
      optional :field2test, :string, 1
    end
  end
end

module Package2test
  Message2test = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("package2test.Message2test").msgclass
end
