# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: constant_name.proto

require 'google/protobuf'

Google::Protobuf::DescriptorPool.generated_pool.build do
  add_file("constant_name.proto", :syntax => :proto3) do
    add_message "example.broken_const" do
      optional :name, :string, 1
      optional :Constant_1, :string, 2
    end
  end
end

module Example
  Broken_const = Google::Protobuf::DescriptorPool.generated_pool.lookup("example.broken_const").msgclass
end
