# Code generated by protoc-gen-rbi. DO NOT EDIT.
# source: example.proto
# typed: strict

module Example; end

class Example::Request
  include Google::Protobuf
  include Google::Protobuf::MessageExts

  sig do
    params(
      name: String
    ).void
  end
  def initialize(
    name: ""
  )
  end

  sig { returns(String) }
  def name
  end

  sig { params(value: String).void }
  def name=(value)
  end
end

class Example::Response
  include Google::Protobuf
  include Google::Protobuf::MessageExts

  sig do
    params(
      greeting: String
    ).void
  end
  def initialize(
    greeting: ""
  )
  end

  sig { returns(String) }
  def greeting
  end

  sig { params(value: String).void }
  def greeting=(value)
  end
end
