# Generated by the protocol buffer compiler.  DO NOT EDIT!
# Source: example.proto for package 'example'

require 'grpc'
require 'example_pb'

module Example
  module Greeter
    class Service

      include ::GRPC::GenericService

      self.marshal_class_method = :encode
      self.unmarshal_class_method = :decode
      self.service_name = 'example.Greeter'

      rpc :Hello, ::Example::Request, ::Example::Response
    end

    Stub = Service.rpc_stub_class
  end
end
