# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: loweracse.proto

require 'google/protobuf'

Google::Protobuf::DescriptorPool.generated_pool.build do
  add_file("loweracse.proto", :syntax => :proto3) do
    add_message "example.lowercase" do
      optional :example_proto_field, :string, 1
    end
  end
end

module Example
  Lowercase = Google::Protobuf::DescriptorPool.generated_pool.lookup("example.lowercase").msgclass
end
