# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: lowercase.proto

require 'google/protobuf'

Google::Protobuf::DescriptorPool.generated_pool.build do
  add_file("lowercase.proto", :syntax => :proto3) do
    add_message "example.lowercase" do
      optional :example_proto_field, :string, 1
    end
    add_message "example.lowercase_with_underscores" do
      optional :example_proto_field, :string, 1
    end
  end
end

module Example
  Lowercase = Google::Protobuf::DescriptorPool.generated_pool.lookup("example.lowercase").msgclass
  Lowercase_with_underscores = Google::Protobuf::DescriptorPool.generated_pool.lookup("example.lowercase_with_underscores").msgclass
end
