# Code generated by protoc-gen-rbi. DO NOT EDIT.
# source: lowercase.proto
# typed: strict

module Example; end

class Example::Lowercase
  include Google::Protobuf
  include Google::Protobuf::MessageExts

  sig { params(str: String).returns(Example::Lowercase) }
  def self.decode(str)
  end

  sig { params(msg: Example::Lowercase).returns(String) }
  def self.encode(msg)
  end

  sig { params(str: String, kw: T.untyped).returns(Example::Lowercase) }
  def self.decode_json(str, **kw)
  end

  sig { params(msg: Example::Lowercase, kw: T.untyped).returns(String) }
  def self.encode_json(msg, **kw)
  end

  sig { returns(Google::Protobuf::Descriptor) }
  def self.descriptor
  end

  sig do
    params(
      example_proto_field: T.nilable(String)
    ).void
  end
  def initialize(
    example_proto_field: ""
  )
  end

  sig { returns(String) }
  def example_proto_field
  end

  sig { params(value: String).void }
  def example_proto_field=(value)
  end

  sig { returns(T::Hash[Symbol, T.untyped]) }
  def to_h
  end
end

class Example::Lowercase_with_underscores
  include Google::Protobuf
  include Google::Protobuf::MessageExts

  sig { params(str: String).returns(Example::Lowercase_with_underscores) }
  def self.decode(str)
  end

  sig { params(msg: Example::Lowercase_with_underscores).returns(String) }
  def self.encode(msg)
  end

  sig { params(str: String, kw: T.untyped).returns(Example::Lowercase_with_underscores) }
  def self.decode_json(str, **kw)
  end

  sig { params(msg: Example::Lowercase_with_underscores, kw: T.untyped).returns(String) }
  def self.encode_json(msg, **kw)
  end

  sig { returns(Google::Protobuf::Descriptor) }
  def self.descriptor
  end

  sig do
    params(
      example_proto_field: T.nilable(String)
    ).void
  end
  def initialize(
    example_proto_field: ""
  )
  end

  sig { returns(String) }
  def example_proto_field
  end

  sig { params(value: String).void }
  def example_proto_field=(value)
  end

  sig { returns(T::Hash[Symbol, T.untyped]) }
  def to_h
  end
end
