# Code generated by protoc-gen-rbi. DO NOT EDIT.
# source: lowercase.proto
# typed: strict

module Example; end

class Example::Lowercase
  include Google::Protobuf
  include Google::Protobuf::MessageExts

  sig { params(args: T::Hash[T.untyped, T.untyped]).void }
  def initialize(args); end

  sig { returns(String) }
  def example_proto_field
  end

  sig { params(value: String).void }
  def example_proto_field=(value)
  end
end

class Example::Lowercase_with_underscores
  include Google::Protobuf
  include Google::Protobuf::MessageExts

  sig do
    params(
      example_proto_field: String
    ).void
  end
  def initialize(
    example_proto_field: ""
  )
  end

  sig { returns(String) }
  def example_proto_field
  end

  sig { params(value: String).void }
  def example_proto_field=(value)
  end
end
