# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: services.proto

require 'google/protobuf'

require 'subdir/messages_pb'
Google::Protobuf::DescriptorPool.generated_pool.build do
  add_file("services.proto", :syntax => :proto3) do
  end
end

module Testdata
end
