# Code generated by protoc-gen-rbi. DO NOT EDIT.
# source: services.proto
# typed: strict

module Testdata::SimpleMathematics
  class Service
    include GRPC::GenericService
  end

  class Stub < GRPC::ClientStub
    sig do
      params(
        host: String,
        creds: T.any(GRPC::Core::ChannelCredentials, Symbol),
        kw: T::Hash[Symbol, T.untyped]
      ).void
    end
    def initialize(host, creds, **kw)
    end

    sig do
      params(
        request: Testdata::Subdir::IntegerMessage
      ).returns(Testdata::Subdir::IntegerMessage)
    end
    def negate(request)
    end

    sig do
      params(
        request: T::Enumerable[Testdata::Subdir::IntegerMessage]
      ).returns(Testdata::Subdir::IntegerMessage)
    end
    def median(request)
    end
  end
end

module Testdata::ComplexMathematics
  class Service
    include GRPC::GenericService
  end

  class Stub < GRPC::ClientStub
    sig do
      params(
        host: String,
        creds: T.any(GRPC::Core::ChannelCredentials, Symbol),
        kw: T::Hash[Symbol, T.untyped]
      ).void
    end
    def initialize(host, creds, **kw)
    end

    sig do
      params(
        request: Testdata::Subdir::IntegerMessage
      ).returns(T::Enumerable[Testdata::Subdir::IntegerMessage])
    end
    def fibonacci(request)
    end

    sig do
      params(
        request: T::Enumerable[Testdata::Subdir::IntegerMessage]
      ).returns(T::Enumerable[Testdata::Subdir::IntegerMessage])
    end
    def running_max(request)
    end

    sig do
      params(
        request: T::Enumerable[Testdata::Subdir::IntegerMessage]
      ).returns(T::Enumerable[Testdata::Subdir::IntegerMessage])
    end
    def periodic_max(request)
    end
  end
end
